openapi: 3.0.0
info:
  title: Документация API
  description: Сервис загрузки и обработки(уменьшения размера до 100х100) изображений
  version: 0.0.1
servers:
  - url: ""
    description: Heroku Application Server
paths:
  /api/image/{id}:
    get:
      summary: /api/image/{id}
      description: Запрос загруженного ранее изображения
      parameters:
        - in: path
          name: id
          required: true
          description: ID изображения (получить можно в HTTP ответе после успешной загрузки на сервер)
          schema:
            type: integer
            minimum: 1
        - in: query
          name: preview
          required: false
          description: Выдать превью изображения (100x100)?
          schema:
            type: boolean
            default: false
      responses:
        200:
          description: ''
          content:
            image/*:
              schema:
                type: string
                format: binary
        400:
          description: 'Ошибка ввода нечислового ID'
          content:
            application/json:
              example: {"error": "Image id must be integer"}
              schema:
                $ref: "#/components/schemas/error"
        404:
          description: "Изображение не найдено"
          content:
            application/json:
              example: {"error":"Image not found"}
              schema:
                $ref: "#/components/schemas/error"
  /api/image/:
    post:
      summary: /api/image/
      description: Загрузка изображения(-ий) на сервер
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: array
                  items:
                    type: string
                    format: binary
            encoding:
              image:
                contentType: image/*
          application/json:
            schema:
              oneOf:
                - type: object
                  properties:
                    url:
                      type: string
                      format: url
                - type: object
                  properties:
                    base64:
                      type: string
                      format: regex
                      pattern: ^data:image/.+;base64,.+$
            examples:
              base64:
                value: {
                  "base64": "data:image/png;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxITEhUSEhIVFRUVFx0VFhYVEhUaFhYVGhUXGBcfIB8YHSggGBolHhUVITEhJSkrLi4uFx8zODMtNygtLisBCgoKDg0OGhAQGzAfHyUwLS8tLS0rLi0vKy4tLS4tLTItLi0rLS0tLS0yLS0tLS0tLS4vKzAtLS8tKzUtLS0tLf/AABEIAOEA4QMBIgACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAAAQIEBQcGAwj/xABIEAABAgIECgUIBwYHAQAAAAABAAIDEQQhMUEFBhIiMlFhcYGhQpGxwfAHExRikrPR8SNScnOTsuEWJDNTVIIVJTQ1Q6LC0v/EABoBAAIDAQEAAAAAAAAAAAAAAAADAgQFAQb/xAAwEQADAAIBAQYDBwUBAAAAAAAAAQIDEQQxBRIhQVFxImGRExQyocHR8CNCgbHx4f/aAAwDAQACEQMRAD8A2kDIrNc0ASztfegCWlXzQBKs6Nw7KkAEuny5IIys7V80Sv6Or9EETrbUL7kADhl2VS8dyCcrNFUvkg16FWu5BrqbUb7kAE+hz5onLN196NnS1/qiyo6Vx7K0AAORbXNAGRbXNAq0q+aAJaVfNADQMnOuPKfcnS6fLkgCVZ0bh2VJA2/oau2pACkZWdq+abEeHbJbJ9ih0zC9Hh1ujwmbDFa0kjZNV0bGahkiVKhC2w1GzVd+qkpp9EGi+JyxIb948FLPoc+apm4z0GUhSoQN5Lsmeu3apcDDVFfUykQXO2RWT7ZocUvICdOWbr70A5Ftc0AiVdZNht3VoFWlXzUQADItrmgCWdr70AS0q+aAJVnRuHZUgAl0+XJBGVnavmiV/R1fogidbahfcgAOfZVLv+SCcrN1fJBr0atdyDXU2o33IADXmeNaJyzdd+9Gzpa/1RZUdK49laAAHItrmgDItrmgVaVfNAEtKvmgBfSRqSpPOM1ckIAQevw8BA26N3cgHK0qvG1AM802C/cgA/Kg+rZeifRu1oJyahWCgAPqce63ig+rbeg5ujXPxcgjJrFZKAD8yN+ld3Il0r9S5rGLHGDR5tb9LGHRac1p9Y3bhXuXZl09IlEVb1K2dIXAAmIQJXkyAC5fCmPVGhza0mO4WBkgyf2rOqaz7DWH6RSjOM+bbmNqYOF+8zKq1ajjr+4uzw9fiOpwlj7S4lTMmE24NaHOl9p3cAudpuEY0T+LFiP2Oe4jqJkFHJTJV1/JWZmZ6Ik8aXRDMmvaU+SUMQUxCakamkJ5CRTTEVJ6UWlxIRnCiPhn1Hub2FdBQMfKZDllubGbqiNrl9pkj1zXNEJqKia6oQ00atgfyh0aLJtIDoJ1nOZP7TRMcRLauso8ZrwHNcHQzouaQWkXSItXz6puCsLx6O7KgxHMna21rt7TUe1VcnDT/B4AqN5/Kg+rZeuPxZx8hRpQo4EF9mVP6NxO06BncetdgTk1CsFUbioeqRPYH1OPdbxQfVtvQc3Rrn4uQRk1islQAPzI36V3ciXSv1IlPONou3IAB6/DwED1+HgIAytKrxtQDlaVXjagBZM8EoR5huvmEqAGh2XVZJE55mq/cgnKqbVLxcic80Wi/cgAn0OfNE8nNtn8kT6N+tAOTUayUAGhtnws+abEcIYL3EASmSTIAWkk6qkOeIYLnkSAmSTUALSZ2BZVjdjQ6kuMOGSIINQsMQi87NTeJrs6lss8bjVnrS6ebJuNWOrohdDoxLGWGJY532b2t22nZfxaVCuRpLwNyOPOOe7KESoDUEJqZCpGmtDQnJFJCKkRInJFLYipGpCE4pFJMr1I1IQnkJqmmV6kYUJXFIQpJiKnQNcutxTx2iUYiFFnEgWS6cP7Otvq9Wo8khcuJtao4fQFDpTHMbEhuD2PE2uFnjZdJe0snOtn81i+KWM8ShxL3wXH6SH/AOmzsd22G4jYqDSmRGNjMcHw3ibSP1sIkRK4rKzYXjfyJp7PaXT5ckSnn6rtyJdK7UgiecLBduSDoSy67JcUTy6rJcUEZWjV42IJytGrxsQAejbeSEnmXa+ZQgBT6nHwUbtK/vQatGvmiysaV47akAH5kD1rbkbelq/Rczj1h70eBktMo0WbW62M6TuchtOwoG4cVZbUT1ZzeP2MhiONGhuzGGURw6Tx0fsg26yNlfGJoSomj12LjThhRP8A0UlKGoaJlWeA8FRKVEEKENribGNvJ7JXp80Ly6lbfQgGQBu49XG1S4GBaVErZR4pFx826XWRIrWcA4q0eigFrcuJ/MeJu/t+oN3ElXi79vroYmXtBb+BfUxD9mab/TRfZR+zNN/povsrb0I+8V6CHzqfkjEP2Ypv9NF9lJ+zFN/povsrcELv3mvQg+XT8kYf+zFN/povspP2Ypv9LF9lbihH3qvQg+Q35GG/svTf6aL7KY7Fqmf00X2dS3KI+Q8a5dS8PN5xBNZrnLfK+oiS797r0IPI2YZFxfpbazR40rZiE4iW3JsUDJlVqqO9fRYCqsOYuUalCUWGMqUhEbIRG8b9xmNinHL8fiRBvZg5CFd4z4uxaHEyX5zHaEQCQcNR1OGpUhCvzSpbRByC6nEXGb0WJ5uKfoIhzp/8brA8bLjsrur5ZCLhWtMifQw19DlK5B2aN/euI8muMBiw/RIpzoYmwm+GLt7TIbiNS7cmVQ0bz21rGyQ4pyxiA+px8FB9Tj4KCZaNfNBq0a+agAkn+CEI84/VyQgBSMiu2aJSztfehoyK7Z6kASztfegBHEAGITKQmdQA+SxPGPC5pVIfGOic1g1Qxo9dZO1xWh+UbCHm6KWtMnRzkbcgDP5Sb/esmSMl+Oj0/YXE+Csz6vwXt5/z5D05gmmApWlE0bVyexdITn+q2XEzA/o1GaCPpIgD4hvmRU3c0Vb5m9ZDgxgiR4LCKnRWNIuk57Qe1b2nJ7PO9s25Ux6+LOcxvxobQ2hrQHxnibWmwCzKdK7UL5HaVmFOxhpcUzfSIm5ryxo4NkF6Y3UsxKZHcbohhjYGHIH5SeJVTanRpDeLw4x402ttkj/EY386L+K/4o/xGP8Azov4r/ioyE+WNrGvQk/4jG/nRfxX/FH+Ixv50X8V/wAVFQmrQisa9CV/iMb+dF/Ff8U12Eo386L+K/4qOgial4CKhHr6fGM5xov4r/ilFOjD/mi/iv8AivBoXdYkYmw48P0ikTLHEhjAS2YBkSSK7QZASsnXNFVMLbK2Tuwts5Si4dpUI5TKRFG+I5zeLXTaeIWk4lY4+lHzMYBsYCYIqbEAtkLnC0jiLwIWM+IUDzLolFBY9gLsjKc5rwBMjOJIdqrl1zGdYPpZgxYcVprY4PHAzI3ETHFL1GafDqVmptbRt+MOCWUqA+C68Ta76rxonr6wSL1g8WGWktcJOaS1w1EGRHWF9FLEMd4IZT6QBZlh3F7GvPNxUeHb25EJbKEhInkJpC0ExdSSMG058CKyMzSYZjbrG4gkcVu1BprYkNj4dbIjQ4G+Tu8LAFpnkrwtlQolFdaw5bPsPOd1Or/vVTmY9z3l5HJZ3TjkbZoIyNs0A5Ftc0AZG2azSYnpJ1ITvSRqSoA8wMnSrHXJOGs6N3cgevw8BI0V16N3cgDNPKFSvOUnIGjCaGgXZTgHO7WjguPjw1e4UjZcV7/rvJHEzA6pKqeyfjxUst5N02e54n9LFMLyX/SvTwV7RIKjkSTpov8AhSLLAH+qo/38L3rVvKwTF8/vVH+/he9at7VrG9o8r28tZI9mYRjB/qqT9/F965QVNw//AKuk/fxfeuUFTVGxE/BPshyRC1bErFJsBrY8doMciYBrEIf/AHrN1gvJcr0U+XnnBO6/wjlcC4hUmMA6IRAYfrCcQj7NUuJB2LqKN5OaI0Z74rztcAP+o711dLpTITS+I9rGi1ziAOa5SneUOjMJDGRIm2Qa07soz5I79voYn2/Jzv4fy/cdH8nVDcM0xWbng/mBXOYY8nkeGC6A8RgOiRkv4TMndY3K8ovlIo5MokKKwaxkuA3yM+oFdZg7CMKOzLgxGvbrBsOoi1p2Fd7+SepCr5GL8X5mCxIZaS1wLXAyIIIIOog1grUfJ1h2E6jtoznBsWHMAEyy2kkgjXKciNk71YY3YrQ6WwuaA2O0Zr/req7WNto6wcfjwXNc5j2kOaS1zTaCDIhP2s06H7nkRrozaMasPQqNBfNwMRzSIbJ5xcRIGVzRee+SxEirgnAIdYmYsahEZw9xH0LZu7P0WL4/f7hSN7Pcw1tSxbH0f5hSN7Pcw1X4v437FPEts55NcUrnJgE71o7JVIpCu8Sad5mmwjOQefNO3PzR1OyTwVLJAJBmKiKwdRFi613paK9To+hBVpV80AS0q+a8KBSBFhMiOsexrxuc0G7evcevw8BYh0XzjNXJCJM8EoQAgOVpVeNqi4TpGTCiH6rHEazktMlIiRMoau8moKsw24mDGaR0JW8FG3qWyeNbtL5ozKJCr3pj4asHQQvCIxYc0eyiitiQ1EjQlaxGKNEhp80Wos8MAiVLo338L3rVviw7A0P96o/38P3jVuK0OPW0zA7fe7j2Zg2MH+rpP38X3rlBBU3D5/e6T9/F965QUKvE3sc/059l/o67yb4JEakmK4TZAAdsMQzyOqTnbw1apS6S2Gx0R5k1gLidgHMrk/JZRw2iOfe+K48AGtHYetHlRphZRmQwf4kQA7WtBdLrDU5dDy3LT5HN+z8t6+nX9ThsYcPRKXE84+YYDmQ51MHYXGdZ7lSpS8oCdNG2sSie7K0hFNwPhWLRogiwnSItHRe3U4XjsuUJCcnsVeNNaZu+BcJspMFkZljhWDa1wqcDtBmuE8qWCQ17KU0af0cT7QE2HiAR/aF7+Seln6eCbBkxBvM2u/KxdDj9Rw+gxtbcl4/te0nlMcUqfgyGB3fseR3V6/kzGkjrEqHWK9s0ak+hli2P5/zCkb2e5hrZoj5SF5qHasXx6H+YUif1me5hqnxvxP2MrjrdP2Oeya5ePmnpQ1BV9D6kaUhT00hTTK9SbNiPE85QYBJ0Wlnsuc3/AMq8BytKrxtXL+TduVQWCei9463T711E8uqyXFZGVat+4hi+Ybr5hKm+jbeSFABHEPqA3zvUHCzB6PFbfk1k7Nt6nn1OPgrwpzA6E9o0i0g9VahkW4a+RPG9Wn80Z29i8HsVg9ijvYvOzR6qaK6IxR4jFYvYo0RidNFibPPA7P3mB99D941bOshwSz94gfew/eNWvLT4b3LMTtp7uPYwTGJsqXSfv4vvXKACrnGNn7zSPvonvHKmexRVeJ6nA1WOfZf6Na8lscOoZaOhFcDxDXf+l4eVajk0eHEFjIkjsDmkdoaOKoPJbhYQ47oDjIRhNv3jZmXFpPshaZhSgMjwnwX6L2yOsaiNoMiNytw9yeU5afF5/ffTe/8AD6/qYGhTMMYLi0aKYMUViw9F7bnDYeVihrqo9F4UlU+KY5IkUihUR8Z7YcNpc9xkAO06gLynTQi0kts7jyT0Y5UeLdJrBvrc7qGT1rp8e4wbQY5N4DRvc9re9TMW8ENosBsEGZGc931nnSO64bAFyHlUwoJQ6K01z86/YKwwcZuPAa0J96zze/vHK3PTf5IztI6xPa2aY8K6ma1SfQrmgiRWMY8tlT442s9zDW0rGMfP9wpG9nuYarcb8TMXhrdv2/YoEiVCuplypGoSpFJMRUmseTiETQWyqz3/AJpdy6gnK0avGxUOI8EtoMANvDnH+57nDkQr4+px8FZeR7t+5QrqxPMu18yhEn+CEKBwU1aNfNBAlMWm0dtSCMiu2aJSztfegDh6RByXFuokdRUV7FfYbg/SF1zxldx7OaqnsXl8i7mRz6M9Fhyd6UyvexR3sVg9i8HsUpotTR44LZ+8QfvWfnC1J8UCoVmyW2U1mdBqjQvvGH/uFoxbnSnOd8uR6qitfgPcsye1Xup9jHsOMnSY5n/yxPeHxJVsSEugw2z94jfev/O5VcSGq/e+Jno+PWon2RUyc1wc0kFpDgRaCDMEbQQtixMxqZS4Ya4hsdoz2WZXrN1g3i4mWonKYkNRmlzHB7HFrmmbXNJBB2EKziy6Dm8OOZj0/Cl0f88jdsL4Ig0lmRGYHC0GxzTrBFYK4mm+TKucGkSGqIyZ9ppHYo2A/KU9oDKVDy5VechyDuLTIHeCNy6ujY70B4/j5Ox7Ht7RI8CraqWee+x5/DfdlPXy8V/5+RzdF8mbp/S0kS1Mh19bjIdRXZYDwBAorZQWSJ0nure7edWwSGxQ4+OlAaJmkNOxrXuP/UFc5hjykiRbRYRn9eLYNzQa+JG5S2iFTzuV4Unr20v0Orxlxgh0SHlOref4cOdbj3NF575A43S6Q+NEdFiGbnnKcd8hVqAEgNQASUqkxIzzEiuc9xtceQ1AbBVWmTqnLh4uTJejS43CXHn1p9WDjIWdq8nm1CRyfNDqg+hljGPn+4Ujez3MNbOsYx8/3Ckb2e5hqHH/ABGBwFvI/b9UUKRCVXDRqREhCVW2KlB89S4LLssOd9luceuUuK660tle1pbNewbRvMwYcJteQxrTfW1oHcvWLFA/hmZvlXIAifGuxLGjZFQImbZ3LyawNMgZ7dcpaulXassyBvpDvW62oUr0k6kIAUDIrNc0ASztfegCWlXzQBKs6Nw7KkAV+G6PlM84LjysPYFzr2LsXsnP6htGyw1Ll6TByXFuqzaLlh9qYe7ayLz6+5p8LL4dz0K97FGjCXYrF7FHeyazpo0poh0FsozCbA9hOyTh8FpTYYFfj4TWcmDISXeYIpvnYTXX2O+0Leu3itjs7IvGTP7RltTRnWMMAtpEYH67ncHHKHIhVL2LScZ8A+flEhy84BKVgeO4hcFS6M6Gcl7S06nCR52qGbHWO3voanC5U5MaSfiuqKqJDUaJDVk9oUaI0KM0akWVUWEvIFWMRoUOMwawrMWWprfUYE9o5LwEUax1hPbFFoI61YmiN42e5dYQkLivN0UG8daA8ax1p00V6xjwvSjQDEe2G217gwb3EAdqZAYXuyWAvcbGtBc48BWtJxGxQfCcKTSRJ4/hw6iWzEsp3rSmALp112OVGfy80YIbb8fJHdrFcd4gdT6QR9Zo4thsaeYK1/C2EGUeC+M/RYJ7zYANpMhxWE0iM573PdpPcXu+04knmVLF4PZjdmY23V+XQ8kJUitqjTqRV3vkzoMvORyK3/QwyRVLSedteSP7SuGolHdEe2GwTc8hrRtPcttwZg9kGAyjgaLZAyrJtnsJJJ4pee9Tr1Mzm13Z7vqe0EZMwa65zFx8HuXoyGGV66ksMBok6vVUlAlpV81TMsX0kakqTzjNXJCAEHr8PAQNujd3IBytKrxtQDPNNgv3IAPyqvwvRMoZTBoivdf1Kwn0btaCcmoVgpWbFOWHFeZPHbilSOScEx7VZ4WoOQcpuieR1KvXlsuOsVuaNrHkVT3kRXsXrg2nugPyhWDpN1j4pzmrwexSx5HLTXUa0qXdrodtQadDiibHT1jpDeFIc0G0A71ndYMwSCLCCQR1KUzDlJbUIhO9rTzlNbOPtGWvjX0KF9nPfwP6namjsHQbL7IS+js+o32QuHdjJSvrj2G/BeLsZqUOmPYb8E5c3E/JnF2bnfmvq/2O+9GZ9RvshMiQYY6DfZFiz2JjdSxZEbP7ttvUorsbaYT/ABB+Gz4eJKa5eNkl2XyH5r6v9jTRRYZ6DfZHwS+iw/qN9kLLzjjTRZEb+Gz4LxiY8U+6I38JnwUlyIY1djcl+a+r/Y1b0WH9RvshHosP6jfZCyE4/U/+Yz8JqcMfqf8AzG/hM+Cmsskn2Hyl5r6v9jYGQwLABuACjYSwlCgMMSM8MaNdpOoC1x2BZJHx3p7hLz+T9mHDB6y0qjpNKfEdlxHue76z3Fx53bFNWmdx9iZN7yUtfLxL/G7Gd1MeGtBbBYZsabXGzKdttkLprnUiUlMmjWnBOOVMrwBK1s05rNdivcV8AupUSREoTDOI4TE/VG0y6q9Ser0IzVMS6fQ6DycYClOlvGdW2CDbKx7u0D+7WF3u/Su7k2HCDWjJAEgAGiwCyUtydKecbRduSKrvPZ5nNleW3TAevw8BA9fh4CAMrSq8bUA5WlV42qIoWTPBKEeYbr5hKgBs8uqyXFE55mq/cgnK0avGxE55otF+5ABPoc+aJ5ObbP5In0b9aAcmo1koAbFhgAtcMoOtFi5/CFBMM62mw9x2rohm6Vc/F6bEhCRyxNpqkqnL4k559GujH4Mzxv5HKJrmqwp+DizObWzXeN/xUFecyY7xV3aWma0WqW5Iz2LwexTnNXi9iJofNFe9ijRhJWEYS7FEdDrIPjV2J80OmyuiQ699/jkmPhqe6CF4xGJyofFFdEhqLEhqzexR4kNOmizFlTGhKMRJWsSGosWErEWW4vfUjApUxwknAqxNHakcCnsbNMaOSvsXMXItKcCJshCp0QiqU6w0dJ3LXqL5op57nHLqnpHjgPBESkvDGCQGm42Mbr2zrzbzxI1zBeDYdFhtZDGaOsk2km8mSXBeDodFhiGxsm9ZJvJJtJqUoDJrNYKbs8lzOY89aXhP86hLp8uSJTz9V25EuldqQRPOFgu3LhSCWXXZLiieXVZLigjK0avGxBOVo1eNiAD0bbyQk8y7XzKEALOeh460btK/vQatGvmiysaV47akAH5kD1rbkbelq/RArrdUbrkAA9fh32cED1rLkCvTq1XIBnU6oXXIAN+gq2m4KDpuh1bLv0VlO7o6/wBUEyqGjee2tKzYIyzq1snGSoe5OViwy0ycJFeTmrrI0MESkHC+qar6Xgdp/hnhaPisbN2Zc+ON7X5mhj5kv8Xgc49k1H81JXMfB0QdGf2a+ysKBEYqLm4eqWi9GSa8U9le9i8HsVg9ijvYmTRZmiuiMXg9isXsUaIxOmh80V8SGosSGrN7FIo2AKRF0ITpa3DJHO3grEbfQd9tMLdPRzUWEvGBRIj3hkNjnuNjWgk/oNq0Si4jNEjGiZd5ZC73GvqAXXYPwdBgsAgMa3WBaTtvJ3q9jw15+BUzduYsa1jXef0X8/mzi8W8QZSfSznWiC03+s4W7hVtNi72DDa0Bsg2VTQBUBdKVQCdt6Wr9ECut1RuuVtSl0POcnl5eRXeyP8Ax5IB6/Dvs4IHrWXIFenVquQDOp1QuuXSsH5UHZo396J3dHX+qCZVDRvPbWgAPqcfBQfU4+CgmWjXzQatGvmgBJP8EIR5x+rkhACkZFds0Slna+9AGRWa5oAlna+9ABLp8uSAMrO1fNEuny5IIys7V80AAz7apd/yQDlZur5IOfZVLv8AkgnKzdXyQAT6HPmgmWbr70T6HPmics3X3oACcjbNBGRXbNAORbXNAGRtmgAlLO196a+C1wynAHYQCNV6cBLO196JdPlyXGk+oJ6IhwXBeJ5AG6Y7FHbgKA6dRG5x71ZkZWdq+aDn2VS7/klPj4n/AGr6DVnyLpT+pUsxfgEyk72yvRmAqMDk+aB2lzj2mSsicrN1fJE+hz5rqwY10lfQ6+Rlf9z+p4QaLDhnJYxrZ3hoBr3J8WNkVCsmfAy/RLEihoyJ1nlO/hbwXi0BplOc65iXUeqo3JiSXQU234sVrJGYJ43crbdy9w3JGUOrelaMi2uaAJZ2vvXTgS6fLkgDKztXzRLp8uSCMrO1fNAAM+2qXf8AJAOVm6vkg59lUu/5IJys3V8kAE+hz5oJlm6+9E+hz5onLN196AAnI2zQRkbZoByKrZoAyK7ZoAPSDqQl9JGpKgBKVYERNAcEIQAN0PGtFH0T4uSoQA2iX8O9JR9I+L0IQADT8akRNMcO1KhACUq0J1KsCVCAEiaA4IboeNaEIAKPonxckol/DvQhACUfSPi9DdPxqQhAHhH0j9tv/lLSNMbj2hCEASKVYERNAcEIQAN0PGtFH0T4uSoQA2iX8O9JR9I+L0IQAN0/GpEXTHBCEAFKtCdSrAlQgCMhCEAf/9k="
                }
              url:
                value: {
                  "url": "https://i.pinimg.com/736x/63/44/da/6344da39807836b9f08231ac42ceecb8.jpg"
                }
      responses:
        200:
          description: "В случае загрузки изображения через application/json возвращается один ID, в случае multipart/form-data - массив ID"
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      id:
                        type: integer
                        minimum: 1
                        example: 23
                    required:
                      - id
                  - type: object
                    properties:
                      id:
                        type: array
                        items:
                          type: integer
                          minimum: 1
                        example: [1, 3]
                    required:
                      - id
        400:
          description: 'Ошибка обработки изображения'
          content:
            application/json:
              example: {"error":"Incorrect base64 data. Must be 'data:<content-type>:base64,<encoded>'"}
              schema:
                $ref: "#/components/schemas/error"


components:
  schemas:
    error:
      properties:
        error:
          type: string
          description: Сообщение об ошибке
      required:
        - error